#!/bin/bash

# Allow VCAP_REPO to be overriden for testing
VCAP_REPO=${VCAP_REPO:-https://github.com/eparreno/vcap.git}

export rvm_trust_rvmrcs_flag=1 # Trust all rmvrcs we find

OS=`uname -s`
if [[ $OS == 'Linux' ]]; then
    PLATFORM='Linux'
else
    echo "Unknown System, cancelling setup"
    exit 1
fi

echo ""
echo '-----------------------------------------------------------'
echo "($PLATFORM) One Click Installer for VMware's Cloud Application Platform!"
echo '-----------------------------------------------------------'
echo ""

echo "Hopefully this will be the last time you type your password"
sudo ls > /dev/null

echo "Installing dependencies"
sudo apt-get update
sudo apt-get upgrade
sudo apt-get -qqy install coreutils autoconf libtool curl git-core ruby bison build-essential zlib1g-dev libssl-dev libreadline5-dev

if [ ! -f ~/.bash_profile ]; then
# rvm install is going to write into .bash_profile in this
# case and short circuit loading of .bashrc so we need to
# create a proper .bash_profile if its missing
echo "# This file is sourced by bash for login shells.  The following line" >> ~/.bash_profile
echo "# runs your .bashrc and is recommended by the bash info pages." >> ~/.bash_profile
echo "[[ -f ~/.bashrc ]] && . ~/.bashrc" >> ~/.bash_profile
fi

echo "Installing rvm"
curl -s -k -B https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer > /tmp/install_rvm
bash /tmp/install_rvm
rm /tmp/install_rvm

echo "Activate rvm"
if [ "$(id -u)" != "0" ]; then
  rvm_path="$HOME/.rvm"
else
  rvm_path="/usr/local/rvm"
fi
[[ -s "$rvm_path/scripts/rvm" ]] && source "$rvm_path/scripts/rvm"
type rvm | head -1

# remove rake from default and global gems and instead install manually
rm $rvm_path/gemsets/default.gems
rm $rvm_path/gemsets/global.gems

echo "Installing various rubies"
rvm install 1.9.2-p180
rvm --default 1.9.2-p180

rvm use 1.9.2-p180
gem install rake --no-rdoc --no-ri

echo "Getting vcap"
[ -d vcap ] || git clone $VCAP_REPO
cd vcap
git submodule update --init
gem install vmc --no-rdoc --no-ri

echo "Setting up vcap."
cd ~/vcap

sudo setup/vcap_setup

echo "Restarting nginx"
cd ~/vcap
sudo cp setup/simple.nginx.conf /etc/nginx/nginx.conf
sudo /etc/init.d/nginx restart

echo "Installing bundler"
cd ~/vcap
gem install bundler --no-rdoc --no-ri
rake bundler:install

# don't start up vcap in this shell
# its best to exit the shell and then
# come back in so that the .rvmrc in cloudfoundry/vcap activates correctly

echo 'Success!'
